apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: busybox
  name: newpods-74lmg
  namespace: default
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    imagePullPolicy: Always
    name: busybox

