apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql
  name: mysql-db
  namespace: dev
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: paswrd
    image: mysql
    imagePullPolicy: Always
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: payroll
  name: payroll
  namespace: finance
spec:
  containers:
  - env:
    - name: APP_NAME
      value: Payroll Application
    - name: BG_COLOR
      value: blue
    image: kodekloud/webapp-conntest
    imagePullPolicy: Always
    name: payroll
    ports:
    - containerPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: red-app
  name: red-app
  namespace: manufacturing
spec:
  containers:
  - env:
    - name: APP_NAME
      value: Red - Manufacturing Application
    - name: BG_COLOR
      value: red
    image: kodekloud/webapp-conntest
    imagePullPolicy: Always
    name: red-app
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: blue
    name: blue
    namespace: marketing
  spec:
    containers:
    - env:
      - name: APP_NAME
        value: Blue - Marketing Application
      - name: BG_COLOR
        value: blue
      image: kodekloud/webapp-conntest
      imagePullPolicy: Always
      name: internal
      ports:
      - containerPort: 8080
        protocol: TCP
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: mysql
    name: mysql-db
    namespace: marketing
  spec:
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
      image: mysql
      imagePullPolicy: Always
      name: mysql
      ports:
      - containerPort: 3306
        protocol: TCP
kind: List
metadata: 
---

apiVersion: v1
kind: List
metadata:
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: dna-1
    namespace: research
  spec:
    containers:
    - image: busybox
      imagePullPolicy: Always
      name: busybox
- apiVersion: v1
  kind: Pod
  metadata:
    name: dna-2
    namespace: research
  spec:
    containers:
    - image: busybox
      imagePullPolicy: Always
      name: busybox
