apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: blue-service
    namespace: marketing
  spec:
    ports:
    - nodePort: 30082
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: blue
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: db-service
    namespace: marketing
  spec:
    ports:
    - nodePort: 31769
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: mysql
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: db-service
    namespace: dev
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: mysql
    type: ClusterIP
kind: List
metadata:
