apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: default
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
  - image: agentx
    imagePullPolicy: Always
    name: agentx
